status = [
  "build (ubuntu-latest, stable)",
  "build (ubuntu-latest, nightly)",
  "build (windows-latest, stable)",
  "build (macOS-latest, stable)",
  "continuous-integration/travis-ci/push",
]
use_squash_merge = true
