[package]
authors = [
    "Without Boats <lee@libertad.ucsd.edu>",
    "Pascal Hertleif <killercup@gmail.com>",
    "Sebastian Garrido <sebasgarcep@gmail.com>",
    "Jonas Platte <mail@jonasplatte.de>",
    "Benjamin Gill <git@bgill.eu>",
    "Andronik Ordian <write@reusable.software>",
]
categories = [
    "development-tools",
    "development-tools::cargo-plugins",
]
description = "This extends Cargo to allow you to add and remove dependencies by modifying your `Cargo.toml` file from the command line. It contains `cargo add`, `cargo rm`, and `cargo upgrade`."
documentation = "https://github.com/killercup/cargo-edit/blob/master/README.md#available-subcommands"
homepage = "https://github.com/killercup/cargo-edit"
keywords = [
    "cargo",
    "cargo-subcommand",
    "cli",
    "dependencies",
    "crates",
]
license = "Apache-2.0 OR MIT"
name = "cargo-edit"
readme = "README.md"
repository = "https://github.com/killercup/cargo-edit"
version = "0.8.0"
edition = "2018"

[[bin]]
name = "cargo-add"
path = "src/bin/add/main.rs"
required-features = ["add"]

[[bin]]
name = "cargo-rm"
path = "src/bin/rm/main.rs"
required-features = ["rm"]

[[bin]]
name = "cargo-upgrade"
path = "src/bin/upgrade/main.rs"
required-features = ["upgrade"]

[[bin]]
name = "cargo-set-version"
path = "src/bin/set-version/main.rs"
required-features = ["set-version"]

[dependencies]
concolor-control = { version = "0.0.7", default-features = false }
cargo_metadata = "0.14.0"
crates-index = "0.18.1"
dunce = "1.0"
dirs-next = "2.0.0"
env_proxy = "0.4.1"
error-chain = "0.12.4"
git2 = "0.13.22"
hex = "0.4.2"
regex = "1.3.9"
serde = "1.0.116"
serde_derive = "1.0.116"
serde_json = "1.0.58"
clap = { version = "3.0", features = ["derive", "wrap_help"], optional = true }
subprocess = "0.2.6"
termcolor = "1.1.0"
toml_edit = { version = "0.13.3", features = ["easy"] }
url = "2.1.1"
ureq = { version = "1.5.1", default-features = false, features = ["tls", "json", "socks"] }
pathdiff = "0.2"

[dependencies.semver]
features = ["serde"]
version = "1.0.0"

[dev-dependencies]
predicates = { version = "2.0.3", features = ["color-auto"] }
assert_cmd = { version = "2.0.2", features = ["color-auto"] }
assert_fs = { version = "1.0.6", features = ["color-auto"] }
pretty_assertions = "0.6.1"
trycmd = "0.12.1"

[features]
default = [
    "add",
    "rm",
    "upgrade",
    "set-version",
    "vendored-libgit2",
]
add = ["cli"]
rm = ["cli"]
upgrade = ["cli"]
set-version = ["cli"]
cli = ["color", "clap"]
color = ["concolor-control/auto"]
test-external-apis = []
vendored-openssl = ["git2/vendored-openssl"]
vendored-libgit2 = ["git2/vendored-libgit2"]
