[package]
authors = ["Without Boats <lee@libertad.ucsd.edu>", "Pascal Hertleif <killercup@gmail.com>", "Sebastian Garrido <sebasgarcep@gmail.com>", "Jonas Platte <mail@jonasplatte.de>"]
description = "This extends Cargo to allow you to add and list dependencies by reading/writing to your `Cargo.toml` file from the command line. It contains `cargo add`, `cargo rm`, and `cargo list`."
documentation = "http://killercup.github.io/cargo-edit/"
homepage = "https://github.com/killercup/cargo-edit"
keywords = ["cargo", "cargo-subcommand", "cli", "dependencies", "crates"]
license = "Apache-2.0/MIT"
name = "cargo-edit"
readme = "README.md"
repository = "https://github.com/killercup/cargo-edit"
version = "0.1.6"

[[bin]]
name = "cargo-list"
path = "src/bin/list/main.rs"

[[bin]]
name = "cargo-add"
path = "src/bin/add/main.rs"

[[bin]]
name = "cargo-rm"
path = "src/bin/rm/main.rs"

[dependencies]
curl = "0.2.18"
docopt = "0.6"
pad = "0.1"
quick-error = "1.0.0"
regex = "0.2"
rustc-serialize = "0.3"
semver = "0.2"
toml = "0.4.2"

[dependencies.clippy]
optional = true
version = "0.0.104"

[dev-dependencies]
assert_cli = "0.2.0"
tempdir = "0.3"

[features]
default = []
dev = ["clippy"]
test-external-apis = []
