[package]
name = "cargo-edit"
authors = ["Without Boats <lee@libertad.ucsd.edu>", "Pascal Hertleif <killercup@gmail.com>"]

version = "0.1.1"

description = "This extends Cargo to allow you to add and list dependencies by reading/writing to your `Cargo.toml` file from the command line. It contains `cargo add`, `cargo rm`, and `cargo list`."
readme = "README.md"
keywords = ["cargo", "cargo-subcommand", "cli", "dependencies", "crates"]
license = "Apache-2.0/MIT"

documentation = "http://killercup.github.io/cargo-edit/"
homepage = "https://github.com/killercup/cargo-edit"
repository = "https://github.com/killercup/cargo-edit"

[[bin]]
name = "cargo-list"
path = "src/bin/list/main.rs"

[features]
default = []
dev = ["clippy"]

[[bin]]
name = "cargo-add"
path = "src/bin/add/main.rs"

[[bin]]
name = "cargo-rm"
path = "src/bin/rm/main.rs"

[dependencies]
docopt = "0.6"
pad = "0.1"
rustc-serialize = "0.3"
semver = "0.1"
toml = "0.1"
hyper = "0.7.1"
quick-error = "0.1.3"
clippy = {version = "0.0.29", optional = true}

[dev-dependencies]
assert_cli = "0.2.0"
tempdir = "0.3"
