name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  check:
    name: check (ubuntu-latest, stable)
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Cargo Check
        run: cargo check

  clippy:
    name: clippy (ubuntu-latest, stable)
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: clippy
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Cargo Clippy
        run: cargo clippy -- -D warnings -A deprecated

  fmt:
    name: fmt (ubuntu-latest, stable)
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: rustfmt
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Check Formatting
        run: cargo fmt --all -- --check
